#%RAML 1.0

# AMWA NMOS Device Connection Management Specification: Connection API
# (c) AMWA 2024

title: Configuration
baseUri: http://api.example.com/x-nmos/configuration/{version}
version: v1.0
mediaType: application/json

documentation:
  - title: Overview
    content: |
      The Configuration API is...
  - title: API Structure
    content: |
      The API presents...
/:
  displayName: Base
  get:
    description: List of paths available from this API
    responses:
      200:
        body:
          example: !include ../examples/base-get-200.json
          type: !include schemas/base.json
/rolePaths:
  displayName: Role Paths
  get:
    description: Returns the name of the root block of the Device Model
    responses:
      200:
        body:
          example: !include ../examples/rolePaths-base-get-200.json
          type: !include schemas/rolePaths-base.json
  /{rolePath}:
    get:
      description: Get attributes of the object specified by rolePath
      responses:
        200:
          body:
            example: !include ../examples/rolePath-get-200.json
            type: !include schemas/rolePath.json
    /properties:
      displayName: Properties
      get:
        description: Get properties of the object
        responses:
          200:
            body:
              example: !include ../examples/properties-base-get-200.json
              type: !include schemas/properties-base.json
      /{propertyId}:
        get:
          description: Get attributes of a property
          responses:
            200:
              body:
                example: !include ../examples/property-get-200.json
                type: !include schemas/property.json
        /value:
          displayName: Value of a property
          get:
            description: Get value of a property
            responses:
              200:
                body:
                  example: !include ../examples/property-value-get-200.json
                  type: !include schemas/NcMethodResultPropertyValue.json
          put:
            descriptions: Set value of a property
            body:
              example: !include ../examples/property-value-put.json
              type: !include schemas/modify-property.json
            responses:
              200:
                body:
                  example: !include ../examples/NcMethodResult-get-200.json
                  type: !include schemas/NcMethodResult.json
        /descriptor:
          displayName: Descriptor of property
          get:
            description: Get descriptor of a property
            responses:
              200:
                body:
                  example: !include ../examples/property-descriptor-get-200.json
                  type: !include schemas/NcDatatypeDescriptor.json
    /methods:
      displayName: Methods
      get:
        description: Get methods of an object
        responses:
          200:
            body:
              example: !include ../examples/methods-base-get-200.json
              type: !include schemas/methods-base.json
      /{methodId}:
        patch:
          description: Invoke method
          body:
            type: !include schemas/invoke-method.json
          responses:
            200:
              body:
                type: !include schemas/NcMethodResult.json
    /members:
      displayName: Members
      get:
        description: List member objects of this object.
        responses:
          200:
            body:
              example: !include ../examples/members-base-get-200.json
              type: !include schemas/members-base.json
    /descriptor:
      displayName: Members
      get:
        description: List member objects of this object.
        responses:
          200:
            body:
              example: !include ../examples/class-descriptor-get-200.json
              type: !include schemas/NcClassDescriptor.json
